version: "2"

run:
  tests: false

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - goconst
    - godot
    - godox
    - goprintffuncname
    - gosec
    - misspell
    - prealloc
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
