version: 2

run:
  tests: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: cmd/
      linters:
        - errcheck

linters:
  enable:
    - asciicheck
    - bodyclose
    - cyclop
    - dogsled
    - dupl
    - errorlint
    - exhaustive
    - goconst
    - godot
    - godox
    - goprintffuncname
    - gosec
    - misspell
    - prealloc
    - sqlclosecheck
    - unconvert
    - unparam
    - whitespace
