package models

type TeamGameStatsResponse struct {
	GameKey                              string  `json:"GameKey"`
	Date                                 string  `json:"Date"`
	SeasonType                           int     `json:"SeasonType"`
	Season                               int     `json:"Season"`
	Week                                 int     `json:"Week"`
	Team                                 string  `json:"Team"`
	Opponent                             string  `json:"Opponent"`
	HomeOrAway                           string  `json:"HomeOrAway"`
	Score                                int     `json:"Score"`
	OpponentScore                        int     `json:"OpponentScore"`
	TotalScore                           int     `json:"TotalScore"`
	Stadium                              string  `json:"Stadium"`
	PlayingSurface                       string  `json:"PlayingSurface"`
	Temperature                          int     `json:"Temperature"`
	Humidity                             int     `json:"Humidity"`
	WindSpeed                            int     `json:"WindSpeed"`
	OverUnder                            float64 `json:"OverUnder"`
	PointSpread                          float64 `json:"PointSpread"`
	ScoreQuarter1                        int     `json:"ScoreQuarter1"`
	ScoreQuarter2                        int     `json:"ScoreQuarter2"`
	ScoreQuarter3                        int     `json:"ScoreQuarter3"`
	ScoreQuarter4                        int     `json:"ScoreQuarter4"`
	ScoreOvertime                        int     `json:"ScoreOvertime"`
	TimeOfPossessionMinutes              int     `json:"TimeOfPossessionMinutes"`
	TimeOfPossessionSeconds              int     `json:"TimeOfPossessionSeconds"`
	TimeOfPossession                     string  `json:"TimeOfPossession"`
	FirstDowns                           int     `json:"FirstDowns"`
	FirstDownsByRushing                  int     `json:"FirstDownsByRushing"`
	FirstDownsByPassing                  int     `json:"FirstDownsByPassing"`
	FirstDownsByPenalty                  int     `json:"FirstDownsByPenalty"`
	OffensivePlays                       int     `json:"OffensivePlays"`
	OffensiveYards                       int     `json:"OffensiveYards"`
	OffensiveYardsPerPlay                float64 `json:"OffensiveYardsPerPlay"`
	Touchdowns                           int     `json:"Touchdowns"`
	RushingAttempts                      int     `json:"RushingAttempts"`
	RushingYards                         int     `json:"RushingYards"`
	RushingYardsPerAttempt               float64 `json:"RushingYardsPerAttempt"`
	RushingTouchdowns                    int     `json:"RushingTouchdowns"`
	PassingAttempts                      int     `json:"PassingAttempts"`
	PassingCompletions                   int     `json:"PassingCompletions"`
	PassingYards                         int     `json:"PassingYards"`
	PassingTouchdowns                    int     `json:"PassingTouchdowns"`
	PassingInterceptions                 int     `json:"PassingInterceptions"`
	PassingYardsPerAttempt               float64 `json:"PassingYardsPerAttempt"`
	PassingYardsPerCompletion            float64 `json:"PassingYardsPerCompletion"`
	CompletionPercentage                 float64 `json:"CompletionPercentage"`
	PasserRating                         float64 `json:"PasserRating"`
	ThirdDownAttempts                    int     `json:"ThirdDownAttempts"`
	ThirdDownConversions                 int     `json:"ThirdDownConversions"`
	ThirdDownPercentage                  float64 `json:"ThirdDownPercentage"`
	FourthDownAttempts                   int     `json:"FourthDownAttempts"`
	FourthDownConversions                int     `json:"FourthDownConversions"`
	FourthDownPercentage                 float64 `json:"FourthDownPercentage"`
	RedZoneAttempts                      int     `json:"RedZoneAttempts"`
	RedZoneConversions                   int     `json:"RedZoneConversions"`
	GoalToGoAttempts                     int     `json:"GoalToGoAttempts"`
	GoalToGoConversions                  int     `json:"GoalToGoConversions"`
	ReturnYards                          int     `json:"ReturnYards"`
	Penalties                            int     `json:"Penalties"`
	PenaltyYards                         int     `json:"PenaltyYards"`
	Fumbles                              int     `json:"Fumbles"`
	FumblesLost                          int     `json:"FumblesLost"`
	TimesSacked                          int     `json:"TimesSacked"`
	TimesSackedYards                     int     `json:"TimesSackedYards"`
	QuarterbackHits                      int     `json:"QuarterbackHits"`
	TacklesForLoss                       int     `json:"TacklesForLoss"`
	Safeties                             int     `json:"Safeties"`
	Punts                                int     `json:"Punts"`
	PuntYards                            int     `json:"PuntYards"`
	PuntAverage                          float64 `json:"PuntAverage"`
	Giveaways                            int     `json:"Giveaways"`
	Takeaways                            int     `json:"Takeaways"`
	TurnoverDifferential                 int     `json:"TurnoverDifferential"`
	OpponentScoreQuarter1                int     `json:"OpponentScoreQuarter1"`
	OpponentScoreQuarter2                int     `json:"OpponentScoreQuarter2"`
	OpponentScoreQuarter3                int     `json:"OpponentScoreQuarter3"`
	OpponentScoreQuarter4                int     `json:"OpponentScoreQuarter4"`
	OpponentScoreOvertime                int     `json:"OpponentScoreOvertime"`
	OpponentTimeOfPossessionMinutes      int     `json:"OpponentTimeOfPossessionMinutes"`
	OpponentTimeOfPossessionSeconds      int     `json:"OpponentTimeOfPossessionSeconds"`
	OpponentTimeOfPossession             string  `json:"OpponentTimeOfPossession"`
	OpponentFirstDowns                   int     `json:"OpponentFirstDowns"`
	OpponentFirstDownsByRushing          int     `json:"OpponentFirstDownsByRushing"`
	OpponentFirstDownsByPassing          int     `json:"OpponentFirstDownsByPassing"`
	OpponentFirstDownsByPenalty          int     `json:"OpponentFirstDownsByPenalty"`
	OpponentOffensivePlays               int     `json:"OpponentOffensivePlays"`
	OpponentOffensiveYards               int     `json:"OpponentOffensiveYards"`
	OpponentOffensiveYardsPerPlay        float64 `json:"OpponentOffensiveYardsPerPlay"`
	OpponentTouchdowns                   int     `json:"OpponentTouchdowns"`
	OpponentRushingAttempts              int     `json:"OpponentRushingAttempts"`
	OpponentRushingYards                 int     `json:"OpponentRushingYards"`
	OpponentRushingYardsPerAttempt       float64 `json:"OpponentRushingYardsPerAttempt"`
	OpponentRushingTouchdowns            int     `json:"OpponentRushingTouchdowns"`
	OpponentPassingAttempts              int     `json:"OpponentPassingAttempts"`
	OpponentPassingCompletions           int     `json:"OpponentPassingCompletions"`
	OpponentPassingYards                 int     `json:"OpponentPassingYards"`
	OpponentPassingTouchdowns            int     `json:"OpponentPassingTouchdowns"`
	OpponentPassingInterceptions         int     `json:"OpponentPassingInterceptions"`
	OpponentPassingYardsPerAttempt       float64 `json:"OpponentPassingYardsPerAttempt"`
	OpponentPassingYardsPerCompletion    float64 `json:"OpponentPassingYardsPerCompletion"`
	OpponentCompletionPercentage         float64 `json:"OpponentCompletionPercentage"`
	OpponentPasserRating                 float64 `json:"OpponentPasserRating"`
	OpponentThirdDownAttempts            int     `json:"OpponentThirdDownAttempts"`
	OpponentThirdDownConversions         int     `json:"OpponentThirdDownConversions"`
	OpponentThirdDownPercentage          float64 `json:"OpponentThirdDownPercentage"`
	OpponentFourthDownAttempts           int     `json:"OpponentFourthDownAttempts"`
	OpponentFourthDownConversions        int     `json:"OpponentFourthDownConversions"`
	OpponentFourthDownPercentage         float64 `json:"OpponentFourthDownPercentage"`
	OpponentRedZoneAttempts              int     `json:"OpponentRedZoneAttempts"`
	OpponentRedZoneConversions           int     `json:"OpponentRedZoneConversions"`
	OpponentGoalToGoAttempts             int     `json:"OpponentGoalToGoAttempts"`
	OpponentGoalToGoConversions          int     `json:"OpponentGoalToGoConversions"`
	OpponentReturnYards                  int     `json:"OpponentReturnYards"`
	OpponentPenalties                    int     `json:"OpponentPenalties"`
	OpponentPenaltyYards                 int     `json:"OpponentPenaltyYards"`
	OpponentFumbles                      int     `json:"OpponentFumbles"`
	OpponentFumblesLost                  int     `json:"OpponentFumblesLost"`
	OpponentTimesSacked                  int     `json:"OpponentTimesSacked"`
	OpponentTimesSackedYards             int     `json:"OpponentTimesSackedYards"`
	OpponentQuarterbackHits              int     `json:"OpponentQuarterbackHits"`
	OpponentTacklesForLoss               int     `json:"OpponentTacklesForLoss"`
	OpponentSafeties                     int     `json:"OpponentSafeties"`
	OpponentPunts                        int     `json:"OpponentPunts"`
	OpponentPuntYards                    int     `json:"OpponentPuntYards"`
	OpponentPuntAverage                  float64 `json:"OpponentPuntAverage"`
	OpponentGiveaways                    int     `json:"OpponentGiveaways"`
	OpponentTakeaways                    int     `json:"OpponentTakeaways"`
	OpponentTurnoverDifferential         int     `json:"OpponentTurnoverDifferential"`
	RedZonePercentage                    float64 `json:"RedZonePercentage"`
	GoalToGoPercentage                   float64 `json:"GoalToGoPercentage"`
	QuarterbackHitsDifferential          int     `json:"QuarterbackHitsDifferential"`
	TacklesForLossDifferential           int     `json:"TacklesForLossDifferential"`
	QuarterbackSacksDifferential         int     `json:"QuarterbackSacksDifferential"`
	TacklesForLossPercentage             float64 `json:"TacklesForLossPercentage"`
	QuarterbackHitsPercentage            float64 `json:"QuarterbackHitsPercentage"`
	TimesSackedPercentage                float64 `json:"TimesSackedPercentage"`
	OpponentRedZonePercentage            float64 `json:"OpponentRedZonePercentage"`
	OpponentGoalToGoPercentage           float64 `json:"OpponentGoalToGoPercentage"`
	OpponentQuarterbackHitsDifferential  int     `json:"OpponentQuarterbackHitsDifferential"`
	OpponentTacklesForLossDifferential   int     `json:"OpponentTacklesForLossDifferential"`
	OpponentQuarterbackSacksDifferential int     `json:"OpponentQuarterbackSacksDifferential"`
	OpponentTacklesForLossPercentage     float64 `json:"OpponentTacklesForLossPercentage"`
	OpponentQuarterbackHitsPercentage    float64 `json:"OpponentQuarterbackHitsPercentage"`
	OpponentTimesSackedPercentage        float64 `json:"OpponentTimesSackedPercentage"`
	Kickoffs                             int     `json:"Kickoffs"`
	KickoffsInEndZone                    int     `json:"KickoffsInEndZone"`
	KickoffTouchbacks                    int     `json:"KickoffTouchbacks"`
	PuntsHadBlocked                      int     `json:"PuntsHadBlocked"`
	PuntNetAverage                       float64 `json:"PuntNetAverage"`
	ExtraPointKickingAttempts            int     `json:"ExtraPointKickingAttempts"`
	ExtraPointKickingConversions         int     `json:"ExtraPointKickingConversions"`
	ExtraPointsHadBlocked                int     `json:"ExtraPointsHadBlocked"`
	ExtraPointPassingAttempts            int     `json:"ExtraPointPassingAttempts"`
	ExtraPointPassingConversions         int     `json:"ExtraPointPassingConversions"`
	ExtraPointRushingAttempts            int     `json:"ExtraPointRushingAttempts"`
	ExtraPointRushingConversions         int     `json:"ExtraPointRushingConversions"`
	FieldGoalAttempts                    int     `json:"FieldGoalAttempts"`
	FieldGoalsMade                       int     `json:"FieldGoalsMade"`
	FieldGoalsHadBlocked                 int     `json:"FieldGoalsHadBlocked"`
	PuntReturns                          int     `json:"PuntReturns"`
	PuntReturnYards                      int     `json:"PuntReturnYards"`
	KickReturns                          int     `json:"KickReturns"`
	KickReturnYards                      int     `json:"KickReturnYards"`
	InterceptionReturns                  int     `json:"InterceptionReturns"`
	InterceptionReturnYards              int     `json:"InterceptionReturnYards"`
	OpponentKickoffs                     int     `json:"OpponentKickoffs"`
	OpponentKickoffsInEndZone            int     `json:"OpponentKickoffsInEndZone"`
	OpponentKickoffTouchbacks            int     `json:"OpponentKickoffTouchbacks"`
	OpponentPuntsHadBlocked              int     `json:"OpponentPuntsHadBlocked"`
	OpponentPuntNetAverage               float64 `json:"OpponentPuntNetAverage"`
	OpponentExtraPointKickingAttempts    int     `json:"OpponentExtraPointKickingAttempts"`
	OpponentExtraPointKickingConversions int     `json:"OpponentExtraPointKickingConversions"`
	OpponentExtraPointsHadBlocked        int     `json:"OpponentExtraPointsHadBlocked"`
	OpponentExtraPointPassingAttempts    int     `json:"OpponentExtraPointPassingAttempts"`
	OpponentExtraPointPassingConversions int     `json:"OpponentExtraPointPassingConversions"`
	OpponentExtraPointRushingAttempts    int     `json:"OpponentExtraPointRushingAttempts"`
	OpponentExtraPointRushingConversions int     `json:"OpponentExtraPointRushingConversions"`
	OpponentFieldGoalAttempts            int     `json:"OpponentFieldGoalAttempts"`
	OpponentFieldGoalsMade               int     `json:"OpponentFieldGoalsMade"`
	OpponentFieldGoalsHadBlocked         int     `json:"OpponentFieldGoalsHadBlocked"`
	OpponentPuntReturns                  int     `json:"OpponentPuntReturns"`
	OpponentPuntReturnYards              int     `json:"OpponentPuntReturnYards"`
	OpponentKickReturns                  int     `json:"OpponentKickReturns"`
	OpponentKickReturnYards              int     `json:"OpponentKickReturnYards"`
	OpponentInterceptionReturns          int     `json:"OpponentInterceptionReturns"`
	OpponentInterceptionReturnYards      int     `json:"OpponentInterceptionReturnYards"`
	SoloTackles                          int     `json:"SoloTackles"`
	AssistedTackles                      int     `json:"AssistedTackles"`
	Sacks                                int     `json:"Sacks"`
	SackYards                            int     `json:"SackYards"`
	PassesDefended                       int     `json:"PassesDefended"`
	FumblesForced                        int     `json:"FumblesForced"`
	FumblesRecovered                     int     `json:"FumblesRecovered"`
	FumbleReturnYards                    int     `json:"FumbleReturnYards"`
	FumbleReturnTouchdowns               int     `json:"FumbleReturnTouchdowns"`
	InterceptionReturnTouchdowns         int     `json:"InterceptionReturnTouchdowns"`
	BlockedKicks                         int     `json:"BlockedKicks"`
	PuntReturnTouchdowns                 int     `json:"PuntReturnTouchdowns"`
	PuntReturnLong                       int     `json:"PuntReturnLong"`
	KickReturnTouchdowns                 int     `json:"KickReturnTouchdowns"`
	KickReturnLong                       int     `json:"KickReturnLong"`
	BlockedKickReturnYards               int     `json:"BlockedKickReturnYards"`
	BlockedKickReturnTouchdowns          int     `json:"BlockedKickReturnTouchdowns"`
	FieldGoalReturnYards                 int     `json:"FieldGoalReturnYards"`
	FieldGoalReturnTouchdowns            int     `json:"FieldGoalReturnTouchdowns"`
	PuntNetYards                         int     `json:"PuntNetYards"`
	OpponentSoloTackles                  int     `json:"OpponentSoloTackles"`
	OpponentAssistedTackles              int     `json:"OpponentAssistedTackles"`
	OpponentSacks                        int     `json:"OpponentSacks"`
	OpponentSackYards                    int     `json:"OpponentSackYards"`
	OpponentPassesDefended               int     `json:"OpponentPassesDefended"`
	OpponentFumblesForced                int     `json:"OpponentFumblesForced"`
	OpponentFumblesRecovered             int     `json:"OpponentFumblesRecovered"`
	OpponentFumbleReturnYards            int     `json:"OpponentFumbleReturnYards"`
	OpponentFumbleReturnTouchdowns       int     `json:"OpponentFumbleReturnTouchdowns"`
	OpponentInterceptionReturnTouchdowns int     `json:"OpponentInterceptionReturnTouchdowns"`
	OpponentBlockedKicks                 int     `json:"OpponentBlockedKicks"`
	OpponentPuntReturnTouchdowns         int     `json:"OpponentPuntReturnTouchdowns"`
	OpponentPuntReturnLong               int     `json:"OpponentPuntReturnLong"`
	OpponentKickReturnTouchdowns         int     `json:"OpponentKickReturnTouchdowns"`
	OpponentKickReturnLong               int     `json:"OpponentKickReturnLong"`
	OpponentBlockedKickReturnYards       int     `json:"OpponentBlockedKickReturnYards"`
	OpponentBlockedKickReturnTouchdowns  int     `json:"OpponentBlockedKickReturnTouchdowns"`
	OpponentFieldGoalReturnYards         int     `json:"OpponentFieldGoalReturnYards"`
	OpponentFieldGoalReturnTouchdowns    int     `json:"OpponentFieldGoalReturnTouchdowns"`
	OpponentPuntNetYards                 int     `json:"OpponentPuntNetYards"`
	IsGameOver                           bool    `json:"IsGameOver"`
	TeamName                             string  `json:"TeamName"`
	DayOfWeek                            string  `json:"DayOfWeek"`
	PassingDropbacks                     int     `json:"PassingDropbacks"`
	OpponentPassingDropbacks             int     `json:"OpponentPassingDropbacks"`
	TeamGameID                           int     `json:"TeamGameID"`
	TwoPointConversionReturns            int     `json:"TwoPointConversionReturns"`
	OpponentTwoPointConversionReturns    int     `json:"OpponentTwoPointConversionReturns"`
	TeamID                               int     `json:"TeamID"`
	OpponentID                           int     `json:"OpponentID"`
	Day                                  string  `json:"Day"`
	DateTime                             string  `json:"DateTime"`
	GlobalGameID                         int     `json:"GlobalGameID"`
	GlobalTeamID                         int     `json:"GlobalTeamID"`
	GlobalOpponentID                     int     `json:"GlobalOpponentID"`
	ScoreID                              int     `json:"ScoreID"`
}
